### ISSUE TITLE
API Docs für Dev API anlegen

### ISSUE THREAD

**Issue by lwsm99** [THM-ATLAS/spring-backend#93]

**Comment by ninahammer2** [comment]
Die gibt es eigentlich schon, da kommt das Frontend auch ran (nur halt nicht in schön), für ne schönere Lösung müsste man dafür nen Pfad in nginx konfigurieren was ganz ganz doll kopfschmerzen geben wird... ich versuche es mal

**Comment by lwsm99** [comment]
Was wäre denn der unschöne weg? Hab auch bisschen rumprobiert und kam nicht ran

**Comment by ninahammer2** [comment]
Man kann in der doc für den Master branch oben in der suchleiste statt /api-docs/docs /api-dev/api-docs/docs eingibt. Ich Probier nochmal ein bisschen rum. Das problem zu erklären ist ein bisschen schwierig über Text (hat was damit zu tun dass das /api-docs/swagger-ui.html mehrfach umleitet und die eigentliche doc nochmal nen anderen Pfad hat wie swagger…

**Comment by ninahammer2** [comment]
habs geschafft :D
